// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9TFr-SmkEQpPyC5AdcYvXssMtLgzX58',
    appId: '1:177944940463:web:32e1e0148c5a88ced2e95a',
    messagingSenderId: '177944940463',
    projectId: 'chefbot-smartcooker',
    authDomain: 'chefbot-smartcooker.firebaseapp.com',
    databaseURL: 'https://chefbot-smartcooker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chefbot-smartcooker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRtT7rbMJYeNFv1AnYDSchi--VJebrIJ8',
    appId: '1:177944940463:android:d50b9436d3827a64d2e95a',
    messagingSenderId: '177944940463',
    projectId: 'chefbot-smartcooker',
    databaseURL: 'https://chefbot-smartcooker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chefbot-smartcooker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6HHIj8pQEKFNf54vAu2hWqOiPOZJcAsw',
    appId: '1:177944940463:ios:aa3318780e3e6fc6d2e95a',
    messagingSenderId: '177944940463',
    projectId: 'chefbot-smartcooker',
    databaseURL: 'https://chefbot-smartcooker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chefbot-smartcooker.firebasestorage.app',
    iosBundleId: 'com.example.chefbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6HHIj8pQEKFNf54vAu2hWqOiPOZJcAsw',
    appId: '1:177944940463:ios:aa3318780e3e6fc6d2e95a',
    messagingSenderId: '177944940463',
    projectId: 'chefbot-smartcooker',
    databaseURL: 'https://chefbot-smartcooker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chefbot-smartcooker.firebasestorage.app',
    iosBundleId: 'com.example.chefbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9TFr-SmkEQpPyC5AdcYvXssMtLgzX58',
    appId: '1:177944940463:web:4fe2d57ba89349add2e95a',
    messagingSenderId: '177944940463',
    projectId: 'chefbot-smartcooker',
    authDomain: 'chefbot-smartcooker.firebaseapp.com',
    databaseURL: 'https://chefbot-smartcooker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chefbot-smartcooker.firebasestorage.app',
  );

}